version: '3.9'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - DB_ENGINE=django.db.backends.postgresql 
      - DB_NAME=postgres 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres 
      - DB_HOST=db
      - DB_PORT=5432

  backend:
    image: reginaibragimova/foodgramm_backend:v2.11.1989
    container_name: foodgram_backend
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: reginaibragimova/foodgramm_frontend:v2.11.1989
    container_name: foodgram_frontend
    restart: always
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
