version: '3.9'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env  


  web:
    image: reginaibragimova/gatefoodgramm_backends:v2.11.1989
    container_name: foodgram_backend
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: saper663/foodgram_frontend:latest
    container_name: foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./logs/:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    restart: always


volumes:
  postgres_data:
  static_value:
  media_value:
