# Generated by Django 4.0.5 on 2022-09-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_delete_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
